version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: DB_SALES_SYSTEM
    volumes:
      - ./DB_SALES_SYSTEM.sql:/docker-entrypoint-initdb.d/DB_SALES_SYSTEM.sql
    ports:
      - "3306:3306"